"""Write each portal app's env.js and invalidate the shared CloudFront distribution.

Invoked by the app deploy pipelines after they sync build artifacts to S3, and manually from the
runbook in docs/orcaui/README.md.

Every hosted app receives the same runtime config, written to its own bucket. The targets come from
the PORTAL_APP_TARGETS environment variable, generated by CDK from lib/portal/apps.ts, so adding an
app to the portal needs no change to this file.

Event payload (all keys optional):
    {"app": "hub"}                     write only that app's env.js
    {"metadata_api_version": "v2"}     override an API version for this write
"""

import os
import boto3
import json
import logging

ssm = boto3.client('ssm')
s3 = boto3.client('s3')
cloudfront = boto3.client('cloudfront')

logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)


def get_ssm_parameter(name, with_decryption=False):
    """Fetch a SSM parameter"""
    try:
        response = ssm.get_parameter(Name=name, WithDecryption=with_decryption)
        return response['Parameter']['Value']
    except Exception as e:
        logger.error(f"Error fetching SSM parameter {name}: {e}")
        return None


def get_app_targets():
    """Parse PORTAL_APP_TARGETS: [{"id", "bucket", "key"}, ...] in registry order."""
    targets = json.loads(os.environ['PORTAL_APP_TARGETS'])
    if not targets:
        raise ValueError("PORTAL_APP_TARGETS is empty; no portal app is hosted in this stage")
    return targets


def select_app_targets(event, targets):
    """Resolve the event's optional 'app' key to the targets to write.

    No 'app' key means every hosted app, which keeps the documented no-payload invocations working.
    """
    requested = event.get('app') if isinstance(event, dict) else None
    if requested is None:
        return targets

    selected = [target for target in targets if target['id'] == requested]
    if not selected:
        known = ', '.join(target['id'] for target in targets)
        raise ValueError(f"unknown app '{requested}'; hosted apps are: {known}")
    return selected


def update_api_versions(event):
    """Update API versions from event with validation and logging"""
    if not event or not isinstance(event, dict):
        logger.info("No update event data received, skipping API version updates")
        return

    api_version_mappings = {
        'metadata_api_version': 'VITE_METADATA_API_VERSION',
        'workflow_api_version': 'VITE_WORKFLOW_API_VERSION',
        'sequence_run_api_version': 'VITE_SEQUENCE_RUN_API_VERSION',
        'file_api_version': 'VITE_FILE_API_VERSION',
        'htsget_api_version': 'VITE_HTSGET_API_VERSION',
        'case_api_version': 'VITE_CASE_API_VERSION',
        'system_catalog_api_version': 'VITE_SYSTEM_CATALOG_API_VERSION',
        'deploy_status_api_version': 'VITE_DEPLOY_STATUS_API_VERSION',
    }

    # Check if any version keys exist in the event
    if not any(key in event for key in api_version_mappings):
        logger.info("No API version updates found in event")
        return

    # update the environment variables
    for event_key, env_key in api_version_mappings.items():
        version = event.get(event_key)
        if version and isinstance(version, str):
            os.environ[env_key] = version
            logger.info(f"Updated {env_key} to {version}")


def build_env_vars():
    """Assemble the runtime config shared by every portal app."""
    env_vars = {
        'VITE_COG_APP_CLIENT_ID': get_ssm_parameter('/orcaui/cog_app_client_id_stage'),
        'VITE_OAUTH_REDIRECT_IN': get_ssm_parameter('/orcaui/oauth_redirect_in_stage'),
        'VITE_OAUTH_REDIRECT_OUT': get_ssm_parameter('/orcaui/oauth_redirect_out_stage'),
        'VITE_COG_USER_POOL_ID': get_ssm_parameter('/data_portal/client/cog_user_pool_id'),
        'VITE_OAUTH_DOMAIN': get_ssm_parameter('/data_portal/client/oauth_domain'),
        'VITE_UNSPLASH_CLIENT_ID': get_ssm_parameter('/data_portal/unsplash/client_id'),

        'VITE_REGION': os.environ['VITE_REGION'],
        'VITE_METADATA_URL': os.environ['VITE_METADATA_URL'],
        'VITE_WORKFLOW_URL': os.environ['VITE_WORKFLOW_URL'],
        'VITE_SEQUENCE_RUN_URL': os.environ['VITE_SEQUENCE_RUN_URL'],
        'VITE_FILE_URL': os.environ['VITE_FILE_URL'],
        'VITE_SSCHECK_URL': os.environ['VITE_SSCHECK_URL'],
        'VITE_HTSGET_URL': os.environ.get('VITE_HTSGET_URL', None),
        'VITE_CASE_URL': os.environ['VITE_CASE_URL'],
        'VITE_SYSTEM_CATALOG_URL': os.environ['VITE_SYSTEM_CATALOG_URL'],
        'VITE_DEPLOY_STATUS_URL': os.environ['VITE_DEPLOY_STATUS_URL'],

        # API Version
        'VITE_METADATA_API_VERSION': os.environ.get('VITE_METADATA_API_VERSION', None),
        'VITE_WORKFLOW_API_VERSION': os.environ.get('VITE_WORKFLOW_API_VERSION', None),
        'VITE_SEQUENCE_RUN_API_VERSION': os.environ.get('VITE_SEQUENCE_RUN_API_VERSION', None),
        'VITE_FILE_API_VERSION': os.environ.get('VITE_FILE_API_VERSION', None),
        'VITE_HTSGET_API_VERSION': os.environ.get('VITE_HTSGET_API_VERSION', None),
        'VITE_CASE_API_VERSION': os.environ.get('VITE_CASE_API_VERSION', None),
        'VITE_SYSTEM_CATALOG_API_VERSION': os.environ.get('VITE_SYSTEM_CATALOG_API_VERSION', None),
        'VITE_DEPLOY_STATUS_API_VERSION': os.environ.get('VITE_DEPLOY_STATUS_API_VERSION', None),
    }

    # Remove null values
    return {k: v for k, v in env_vars.items() if v is not None}


def handler(event, context):
    """Handler for the lambda function"""

    # read the event to update the api version
    update_api_versions(event)

    cloudfront_distribution_id = os.environ['CLOUDFRONT_DISTRIBUTION_ID']

    try:
        targets = select_app_targets(event, get_app_targets())
    except (KeyError, ValueError, json.JSONDecodeError) as e:
        logger.exception("Could not resolve which portal apps to write env.js for")
        return {'statusCode': 400, 'body': str(e)}

    env_js_content = f"window.config = {json.dumps(build_env_vars(), indent=2)}"

    try:
        written = []
        for target in targets:
            s3.put_object(Bucket=target['bucket'], Key=target['key'],
                          Body=env_js_content, ContentType='text/javascript')
            written.append(f"s3://{target['bucket']}/{target['key']}")
            logger.info(f"{target['key']} uploaded to {target['bucket']} for app {target['id']}")

        # Invalidate the whole distribution. Every app shares it, so an app deploy currently evicts
        # the other apps' cached objects too. Scoping this to /<prefix>/* is tracked in
        # docs/portal/future-improvements.md; it needs the deploy pipelines to pass {"app": "<id>"}.
        cloudfront.create_invalidation(
            DistributionId=cloudfront_distribution_id,
            InvalidationBatch={
                'Paths': {
                    'Quantity': 1,
                    'Items': ['/*']
                },
                'CallerReference': str(context.aws_request_id)
            }
        )

        return {
            'statusCode': 200,
            'body': (f"env.js uploaded to {', '.join(written)}, and CloudFront cache invalidated "
                     f"for {cloudfront_distribution_id}")
        }
    except Exception as e:
        # Log the error and return a failure response (exception includes traceback in CloudWatch)
        logger.exception(
            "Failed during env.js upload or CloudFront invalidation for apps %s",
            ', '.join(target['id'] for target in targets),
        )
        attempted = ', '.join(f"s3://{t['bucket']}/{t['key']}" for t in targets)
        return {
            'statusCode': 500,
            'body': f"Failed to upload env.js to {attempted}. {e}"
        }
